### ISSUE TITLE
Improve UI of landing page

### ISSUE THREAD

**Issue by suhanichawla** [MLH-Fellowship/ACE#38]
The landing page should consist of the rules and icon of the project. Revamp the landing page UI to make it look better.

**Comment by Sameerkash** [comment]
Anything specific ?

**Comment by suhanichawla** [comment]
The only requirement page should contain all the rules and icon for the game.

**Comment by Sameerkash** [comment]
Okay, please assign this to me, I'll take a look and reach out for further doubts.
