### ISSUE TITLE
Keyboard Interrupt to stop speak positions

### ISSUE THREAD

**Issue by suhanichawla** [MLH-Fellowship/ACE#54]
Currently, when speak positions is called there is no way to interrupt the computer speech. It will continue till all the pieces on the board are spoken out. To fix this, when speak positions is going on, user should be able to press esc key to break out of the function.

**Comment by n-maido** [comment]
Hello, @petercrackthecode and I would like to work on this issue-can you assign it to us? Thanks!

**Comment by suhanichawla** [comment]
Hey, sure! Only able to assign to those who have commented, therefore assigned to you. Good luck, let us know if you have any queries

**Comment by petercrackthecode** [comment]
Hey @suhanichawla, can you assign me as well?
